# Generated by Django 4.0.3 on 2022-03-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_markdownimage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdownimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
