# Generated by Django 4.0.3 on 2022-03-21 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_markdown_delete_markdownimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markdown',
            name='img_name',
        ),
    ]
