# Generated by Django 4.0.3 on 2022-03-21 06:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_markdown_img_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdown',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='markdown',
            name='img',
            field=models.ImageField(null=True, upload_to=api.models.load_path),
        ),
    ]
