# Generated by Django 4.0.3 on 2022-03-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_markdown_text_alter_markdown_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdown',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
