# Generated by Django 4.0.3 on 2022-03-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_markdown_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdown',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='markdown',
            name='overview',
            field=models.CharField(max_length=100),
        ),
    ]
