# Generated by Django 4.0.3 on 2022-03-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_markdown_category_alter_markdown_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markdown',
            name='img',
        ),
    ]
