# Generated by Django 4.0.3 on 2022-03-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
